sudo: false
language: python
cache: pip
notifications:
  email: false

python:
  - 3.5
  - 3.6

script: true

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install -e .
  - python setup.py flake8
  - pytest tests --cov=occa

after_success:
  - codecov
