sudo: false
language: python
cache: pip
notifications:
  email: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

script: true

install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py flake8 install sdist
  - pip install $(ls dist/*tar.gz -1 --sort version | tail -n 1)
  - cd tests && pytest .

after_success:
  - codecov
