sudo: false
language: python
cache: pip
notifications:
  email: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

script: true

install:
  - pip install -r requirements.txt
  - python setup.py flake8
  - python setup.py install
